
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author vende
 */
public class LivrosTela extends javax.swing.JFrame {

    /**
     * Creates new form LivrosTela
     */
    public LivrosTela() {
         super("Livros");
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        livrosPanel = new javax.swing.JPanel();
        nomeDoAutorTextField = new javax.swing.JTextField();
        nomeDoLivroTextField = new javax.swing.JTextField();
        cancelarButton = new javax.swing.JButton();
        tipoLivroComboBox = new javax.swing.JComboBox<>();
        cadastrarLivroButton = new javax.swing.JButton();
        deletarLivroButton = new javax.swing.JButton();
        anoLivroTextField = new javax.swing.JTextField();
        exibirLivrosButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        livrosTable = new javax.swing.JTable();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        livrosPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gerenciamento de livros", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N
        livrosPanel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        nomeDoAutorTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Digite o nome do autor "));
        nomeDoAutorTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeDoAutorTextFieldActionPerformed(evt);
            }
        });

        nomeDoLivroTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Digite o nome do livro"));
        nomeDoLivroTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeDoLivroTextFieldActionPerformed(evt);
            }
        });

        cancelarButton.setText("Cancelar");
        cancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarButtonActionPerformed(evt);
            }
        });

        tipoLivroComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ciência e sociedade", "Sustentabilidade", "Tecnologia" }));
        tipoLivroComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoLivroComboBoxActionPerformed(evt);
            }
        });

        cadastrarLivroButton.setText("Cadastrar livro");
        cadastrarLivroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarLivroButtonActionPerformed(evt);
            }
        });

        deletarLivroButton.setText("Deletar livro");
        deletarLivroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletarLivroButtonActionPerformed(evt);
            }
        });

        anoLivroTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Ano do livro"));

        exibirLivrosButton.setText("Exibir livros");
        exibirLivrosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exibirLivrosButtonActionPerformed(evt);
            }
        });

        livrosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nome do livro", "Autor", "Tipo do livro", "Ano do livro", "Usuario responsável"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(livrosTable);

        javax.swing.GroupLayout livrosPanelLayout = new javax.swing.GroupLayout(livrosPanel);
        livrosPanel.setLayout(livrosPanelLayout);
        livrosPanelLayout.setHorizontalGroup(
            livrosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(livrosPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(livrosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(anoLivroTextField)
                    .addComponent(nomeDoLivroTextField)
                    .addComponent(nomeDoAutorTextField)
                    .addComponent(tipoLivroComboBox, 0, 172, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(livrosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, livrosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(exibirLivrosButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cadastrarLivroButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(deletarLivroButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, livrosPanelLayout.createSequentialGroup()
                        .addComponent(cancelarButton)
                        .addGap(17, 17, 17)))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        livrosPanelLayout.setVerticalGroup(
            livrosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(livrosPanelLayout.createSequentialGroup()
                .addGroup(livrosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(livrosPanelLayout.createSequentialGroup()
                        .addGroup(livrosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(livrosPanelLayout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addGroup(livrosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(nomeDoLivroTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(exibirLivrosButton))
                                .addGap(22, 22, 22)
                                .addComponent(nomeDoAutorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tipoLivroComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(livrosPanelLayout.createSequentialGroup()
                                .addGap(137, 137, 137)
                                .addComponent(deletarLivroButton)
                                .addGap(18, 18, 18)
                                .addComponent(cadastrarLivroButton)
                                .addGap(18, 18, 18)
                                .addComponent(cancelarButton)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(anoLivroTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(livrosPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addComponent(livrosPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomeDoAutorTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeDoAutorTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeDoAutorTextFieldActionPerformed

    private void cancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarButtonActionPerformed
          LoginTela lt =  new LoginTela();
          lt.setVisible(true);
         this.dispose();
        
   
    }//GEN-LAST:event_cancelarButtonActionPerformed

    private void nomeDoLivroTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeDoLivroTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeDoLivroTextFieldActionPerformed

    private void tipoLivroComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoLivroComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoLivroComboBoxActionPerformed

    private void cadastrarLivroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarLivroButtonActionPerformed
        // TODO add your handling code here:
        String nome_livro = nomeDoLivroTextField.getText();
        String nome_autor = nomeDoAutorTextField.getText();
        String tipo_livro = tipoLivroComboBox.getItemAt(tipoLivroComboBox.getSelectedIndex());
        String ano_livro = anoLivroTextField.getText();
        String usuario_responsavel = SessaoUsuario.nomeUsuarioLog;
        Livro livro = new Livro(nome_livro, nome_autor, tipo_livro, ano_livro, usuario_responsavel);
        try{
            LivroDAO.cadastraLivro(livro);
            JOptionPane.showMessageDialog(null, "Livro " + nome_livro + " cadastrado com sucesso!");

        } catch(SQLException e){
           e.printStackTrace();
        }
        
    }//GEN-LAST:event_cadastrarLivroButtonActionPerformed

    private void deletarLivroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletarLivroButtonActionPerformed
        // TODO add your handling code here:
        String nome_livro = nomeDoLivroTextField.getText();
        Livro livro = new Livro(nome_livro);
        
        try {
        LivroDAO.deletaLivro(livro);
        JOptionPane.showMessageDialog(null, "Livro '" + nome_livro  + "' removido com sucesso!");
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Erro ao remover o usuário: " + e.getMessage());
    }
    }//GEN-LAST:event_deletarLivroButtonActionPerformed

    private void exibirLivrosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exibirLivrosButtonActionPerformed
        // TODO add your handling code here:
         try{
            List<Livro> livros = LivroDAO.exibirLivros();
            
            DefaultTableModel model= (DefaultTableModel) livrosTable.getModel();
            model.setRowCount(0);
            
            for (Livro l: livros){
                model.addRow(new Object[] {
                    l.getNomeLivro(),
                    l.getAutorLivro(),
                    l.getTipoLivro(),
                    l.getAnoLIvro(),
                    l.getUsuarioResponsavel()
                });
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, "Erro ao exibir livros: "  + e.getMessage());
        }
    }//GEN-LAST:event_exibirLivrosButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LivrosTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LivrosTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LivrosTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LivrosTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LivrosTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField anoLivroTextField;
    private javax.swing.JButton cadastrarLivroButton;
    private javax.swing.JButton cancelarButton;
    private javax.swing.JButton deletarLivroButton;
    private javax.swing.JButton exibirLivrosButton;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel livrosPanel;
    private javax.swing.JTable livrosTable;
    private javax.swing.JTextField nomeDoAutorTextField;
    private javax.swing.JTextField nomeDoLivroTextField;
    private javax.swing.JComboBox<String> tipoLivroComboBox;
    // End of variables declaration//GEN-END:variables
}
