
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import java.util.ArrayList;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author vende
 */
public class UsuariosTela extends javax.swing.JFrame {

    /**
     * Creates new form UsuariosTela
     */
    public UsuariosTela() {
        super("Usuarios");
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usuariosPanel = new javax.swing.JPanel();
        nomeTextField = new javax.swing.JTextField();
        senhaTextField = new javax.swing.JTextField();
        tipoUsuarioComboBox = new javax.swing.JComboBox<>();
        preferenciaLivro1ComboBox = new javax.swing.JComboBox<>();
        preferenciaLivro2ComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        livroPreferido1Label = new javax.swing.JLabel();
        livroPreferido2Label = new javax.swing.JLabel();
        cadastrarUsuarioButton = new javax.swing.JButton();
        alterarUsuarioButton = new javax.swing.JButton();
        removerUsuarioButton = new javax.swing.JButton();
        cancelarButton = new javax.swing.JButton();
        consultarUsuarioButton = new javax.swing.JButton();
        exibirUsuariosButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        usuariosTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        usuariosPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gerenciamento de Usuários", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N

        nomeTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Digite seu login"));
        nomeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeTextFieldActionPerformed(evt);
            }
        });

        senhaTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Digite sua senha"));

        tipoUsuarioComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "admin", "comum" }));
        tipoUsuarioComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoUsuarioComboBoxActionPerformed(evt);
            }
        });

        preferenciaLivro1ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Não se aplica", "Ciência e sociedade", "Sustentabilidade", "Tecnologia" }));
        preferenciaLivro1ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preferenciaLivro1ComboBoxActionPerformed(evt);
            }
        });

        preferenciaLivro2ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Não se aplica", "Ciência e sociedade", "Sustentabilidade", "Tecnologia" }));

        jLabel1.setText("Tipo de usuario:");

        livroPreferido1Label.setText("Preferência de livro 1:");

        livroPreferido2Label.setText("Preferência de livro 2:");

        cadastrarUsuarioButton.setText("Cadastrar");
        cadastrarUsuarioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarUsuarioButtonActionPerformed(evt);
            }
        });

        alterarUsuarioButton.setText("Alterar");
        alterarUsuarioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarUsuarioButtonActionPerformed(evt);
            }
        });

        removerUsuarioButton.setText("Remover");
        removerUsuarioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerUsuarioButtonActionPerformed(evt);
            }
        });

        cancelarButton.setText("Cancelar");
        cancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarButtonActionPerformed(evt);
            }
        });

        consultarUsuarioButton.setText("Consultar");
        consultarUsuarioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarUsuarioButtonActionPerformed(evt);
            }
        });

        exibirUsuariosButton.setText("Exibir usuarios");
        exibirUsuariosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exibirUsuariosButtonActionPerformed(evt);
            }
        });

        usuariosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nome", "Tipo", "Senha", "Preferencia Livro 1", "Preferencia Livro 2"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(usuariosTable);

        javax.swing.GroupLayout usuariosPanelLayout = new javax.swing.GroupLayout(usuariosPanel);
        usuariosPanel.setLayout(usuariosPanelLayout);
        usuariosPanelLayout.setHorizontalGroup(
            usuariosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usuariosPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(usuariosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(livroPreferido1Label)
                    .addComponent(livroPreferido2Label)
                    .addComponent(preferenciaLivro1ComboBox, 0, 237, Short.MAX_VALUE)
                    .addComponent(tipoUsuarioComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(senhaTextField)
                    .addComponent(nomeTextField)
                    .addComponent(preferenciaLivro2ComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(usuariosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(usuariosPanelLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(usuariosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(consultarUsuarioButton)
                            .addGroup(usuariosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(usuariosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(removerUsuarioButton)
                                    .addComponent(alterarUsuarioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cancelarButton))
                                .addComponent(cadastrarUsuarioButton)))
                        .addGap(49, 49, 49))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, usuariosPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exibirUsuariosButton, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        usuariosPanelLayout.setVerticalGroup(
            usuariosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usuariosPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(usuariosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(usuariosPanelLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(consultarUsuarioButton)
                        .addGap(18, 18, 18)
                        .addComponent(cadastrarUsuarioButton)
                        .addGap(18, 18, 18)
                        .addComponent(removerUsuarioButton)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(usuariosPanelLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(nomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(usuariosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(usuariosPanelLayout.createSequentialGroup()
                        .addComponent(exibirUsuariosButton)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(usuariosPanelLayout.createSequentialGroup()
                        .addComponent(senhaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(usuariosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, usuariosPanelLayout.createSequentialGroup()
                                .addComponent(tipoUsuarioComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(livroPreferido1Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(preferenciaLivro1ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(usuariosPanelLayout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(alterarUsuarioButton)
                                .addGap(18, 18, 18)
                                .addComponent(cancelarButton)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(livroPreferido2Label)
                        .addGap(18, 18, 18)
                        .addComponent(preferenciaLivro2ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(usuariosPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(usuariosPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(164, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeTextFieldActionPerformed

    private void tipoUsuarioComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoUsuarioComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoUsuarioComboBoxActionPerformed

    private void cadastrarUsuarioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarUsuarioButtonActionPerformed
            String nome = nomeTextField.getText();
            String senha = senhaTextField.getText();
            String tipoDeUsuario = tipoUsuarioComboBox.getItemAt(tipoUsuarioComboBox.getSelectedIndex());
            String preferenciaLivro1 = preferenciaLivro1ComboBox.getItemAt(preferenciaLivro1ComboBox.getSelectedIndex());
            String preferenciaLivro2 = preferenciaLivro2ComboBox.getItemAt(preferenciaLivro2ComboBox.getSelectedIndex());
            Usuario usuario = new Usuario(nome, senha, tipoDeUsuario, preferenciaLivro1, preferenciaLivro2);
           try{
               UsuarioDAO.cadastraUsuario(usuario);
               JOptionPane.showMessageDialog(null, "Usuario " + nome + " cadastrado com sucesso!");
           }catch(SQLException e){
               e.printStackTrace();
           }
            
    }//GEN-LAST:event_cadastrarUsuarioButtonActionPerformed

    private void removerUsuarioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerUsuarioButtonActionPerformed
         String nome = nomeTextField.getText();
    Usuario usuario = new Usuario(nome);

    try {
        UsuarioDAO.removeUsuario(usuario);
        JOptionPane.showMessageDialog(null, "Usuário '" + nome + "' removido com sucesso!");
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Erro ao remover o usuário: " + e.getMessage());
    }
    }//GEN-LAST:event_removerUsuarioButtonActionPerformed

    private void cancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarButtonActionPerformed
        // TODO add your handling code here:
        LoginTela lt = new LoginTela();
        lt.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_cancelarButtonActionPerformed

    private void preferenciaLivro1ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preferenciaLivro1ComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_preferenciaLivro1ComboBoxActionPerformed

    private void alterarUsuarioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarUsuarioButtonActionPerformed
        String tipo = (String)tipoUsuarioComboBox.getSelectedItem();
        String senha = senhaTextField.getText();
        if (tipo.equals("comum")){
            String preferenciaLivro1 = (String) preferenciaLivro1ComboBox.getSelectedItem();
            String preferenciaLivro2 = (String) preferenciaLivro2ComboBox.getSelectedItem();
            String sql = "UPDATE table_usuarios SET senha = ?,  preferencia_livro_1 = ?, preferencia_livro_2 = ? WHERE nome = ";

        }
        else{
            String sql = "UPDATE table_usuarios SET senha = ? WHERE nome = ?";
        }
    }//GEN-LAST:event_alterarUsuarioButtonActionPerformed

    private void consultarUsuarioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarUsuarioButtonActionPerformed
        String nome = nomeTextField.getText();
        String senha = senhaTextField.getText();
        Usuario usuario = new Usuario(nome, senha);
         try{
             if (UsuarioDAO.consultaUsuario(usuario)){
                 tipoUsuarioComboBox.setSelectedItem(usuario.getTipo());
                        if(usuario.getTipo().equals("comum")){
                            preferenciaLivro1ComboBox.setSelectedItem(usuario.getPreferencia_livro_1());
                            preferenciaLivro2ComboBox.setSelectedItem(usuario.getPreferencia_livro_2());
                        }else {
                            preferenciaLivro1ComboBox.setSelectedIndex(0);
                            preferenciaLivro2ComboBox.setSelectedIndex(0);
                        }
                        
             } else {
                  JOptionPane.showMessageDialog(null, "Usuario não cadastrado", "Erro", JOptionPane.WARNING_MESSAGE);
             }
         }catch(Exception e){
             JOptionPane.showMessageDialog(null, "Problemas técnicos", "Erro", JOptionPane.WARNING_MESSAGE);
         }
    }//GEN-LAST:event_consultarUsuarioButtonActionPerformed

    private void exibirUsuariosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exibirUsuariosButtonActionPerformed
        // TODO add your handling code here:
        try{
            List<Usuario> usuarios = UsuarioDAO.exibirUsuarios();
            
            DefaultTableModel model= (DefaultTableModel) usuariosTable.getModel();
            model.setRowCount(0);
            
            for (Usuario u: usuarios){
                model.addRow(new Object[] {
                    u.getNome(),
                    u.getTipo(),
                    u.getSenha(),
                    u.getPreferencia_livro_1(),
                    u.getPreferencia_livro_2()
                });
            }
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(this, "Erro ao exibir usuarios: "  + ex.getMessage());
        }
        
        
    }//GEN-LAST:event_exibirUsuariosButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UsuariosTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UsuariosTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UsuariosTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UsuariosTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UsuariosTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alterarUsuarioButton;
    private javax.swing.JButton cadastrarUsuarioButton;
    private javax.swing.JButton cancelarButton;
    private javax.swing.JButton consultarUsuarioButton;
    private javax.swing.JButton exibirUsuariosButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel livroPreferido1Label;
    private javax.swing.JLabel livroPreferido2Label;
    private javax.swing.JTextField nomeTextField;
    private javax.swing.JComboBox<String> preferenciaLivro1ComboBox;
    private javax.swing.JComboBox<String> preferenciaLivro2ComboBox;
    private javax.swing.JButton removerUsuarioButton;
    private javax.swing.JTextField senhaTextField;
    private javax.swing.JComboBox<String> tipoUsuarioComboBox;
    private javax.swing.JPanel usuariosPanel;
    private javax.swing.JTable usuariosTable;
    // End of variables declaration//GEN-END:variables
}
